server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        format_sql: true
#        show_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/study_db?serverTimezone=UTC&rewriteBatchedStatements=true&useUnicode=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  config: classpath:logback-spring.xml
